SWIGGY_URL = "https://www.swiggy.com"
CSRF_PATTERN = r"window._csrfToken = \"(.+?)\";"
SWIGGY_COOKIE = "__SW"
SWIGGY_LOGIN_URL = f"{SWIGGY_URL}/dapi/auth/signin-with-check"
SWIGGY_SEND_OTP_URL = f"{SWIGGY_URL}/dapi/auth/sms-otp"
SWIGGY_VERIFY_OTP_URL = f"{SWIGGY_URL}/dapi/auth/otp-verify"
STATUS_FLAG = "statusCode"
CART_URL = f"{SWIGGY_URL}/dapi/cart"
APPLY_COUPON_URL = f"{SWIGGY_URL}/dapi/cart/applyCoupon"
PLACE_ORDER_URL = f"{SWIGGY_URL}/dapi/order/place-v2"
